### ISSUE TITLE
【style.css】必須クラスについて

### ISSUE THREAD

**Issue by mt8** [tomotomo/mtportfolio#10]
- sticky
  
  > 記事を先頭に固定表示した時に付加されます。
  > 目立たせた方がいいのかなー
- gallery-caption
  
  > 画像のキャプションです。
  > wp_captionと同じでよさそう。
- bypostauthor
  
  > 管理者自身のコメントに付加されます。
  > コメントへの管理者の応答を目立たせたりするのかなー

**Comment by tomotomo** [comment]
へぇへぇへぇ〜

**Comment by mt8** [comment]
3へぇ！

**Comment by kozaru** [comment]
へぇへぇへぇ〜
えっと、ちょっと落ち着きつつあるので、今週からやってみます！

**Comment by kozaru** [comment]
とりあえずの形で実装して、https://github.com/kozaru/mtportfolioに。下層ページデザイン当てるときに、デザイン修正予定。
