### ISSUE TITLE
【index.php】js

### ISSUE THREAD

**Issue by mt8** [tomotomo/mtportfolio#11]
仮実装中？だと思うのですが、jsはwp_enqueue_scriptで読み込むように変更しないとダメみたいですー

**Comment by tomotomo** [comment]
え、HTMLに直書きダメなんだっけ？(=o=;)
http://codex.wordpress.org/Function_Reference/wp_enqueue_script

`<script src="javascript.js">`
の時だけ使うんだと思っておったorz

**Comment by mt8** [comment]
過去レビューを見てると指摘されてた？かもなんです。
もうちょっと調べます〜！

**Comment by tomotomo** [comment]
まじかーΣ(´∀｀；)
基準がようわからん。公式テーマのヘッダーの汚さは何故ありなんだと小一時間。。。

**Comment by mt8** [comment]
[sonoichi](http://themes.trac.wordpress.org/search?q=sonoichi)が公式申請した時のレビュー履歴です。

主にこちらで修正要望が出ていた点をチェックしていました。

jsのハードコーディングについてはここでは出ていませんでしたが、

[ここ](http://wp-d.org/2013/02/12/2590/)を見ると、_「やってはいけないこと」_に  

> jsやcssのハードコーディング(フックで設定すること)  

とありますね!sonoichiでは、wp_headでjsを仕込んでますねー！

[参照](http://themes.trac.wordpress.org/browser/sonoichi/1.1.1/functions.php?rev=27944#L185)

**Comment by kozaru** [comment]
先週、Twentythirteen子テーマにjQyeryMasonryを組込をやってて、TwentythirteenにMasonryが入ってることを知りました。（遅い？）

## 参考にしたサイト

・http://wg.drive.ne.jp/miura/archives/2402
・http://wg.drive.ne.jp/miura/archives/2485

中に、wp_enqueue_script使ってたので...一応。
