### ISSUE TITLE
ナビゲーションメニューはフッター上？？

### ISSUE THREAD

**Issue by mt8** [tomotomo/mtportfolio#2]
![2013-11-22 21 51 10](https://f.cloud.github.com/assets/2771396/1600604/0ffa787a-5375-11e3-904d-6cd44a50153b.png)

**Comment by kozaru** [comment]
おーーー、それ、今の分は直ってるんです...どうしよー、めちゃ途中ですが、表示はきれいになるので、pullRequestしたほうがいいですか？

**Comment by tomotomo** [comment]
あとでいいんじゃなーい？
