### ISSUE TITLE
【index.php】CSS media query の値を利用。

### ISSUE THREAD

**Issue by mt8** [tomotomo/mtportfolio#8]
条件が変わったら書きなおさなきゃいけない。不格好

**Comment by kozaru** [comment]
ちょっと先になりますが、直します！ありがとーございます。

**Comment by kozaru** [comment]
とりあえずの形で実装して、https://github.com/kozaru/mtportfolioに。これでいいのかなぁ。ちょっとMasonryへの影響が不安。
