### ISSUE TITLE
【sidebar.php】dynamic_sidebar();

### ISSUE THREAD

**Issue by mt8** [tomotomo/mtportfolio#9]
テーマチェック上では必須のようです。

sidebar.phpで使うべきだと思うのですが、構造上どうでしょうか。

ようは、ユーザがサイドバー設定したものは出そうよ、ということなのかな・・・

**Comment by kozaru** [comment]
ここ、どうするか決めてほしいです。それにあわせて、見た目側も修正が必要なら言ってください！

**Comment by mt8** [comment]
了解です。ようは、ユーザがウィジットを設定しても表示する場所がないよー　っていう状態ですね。
